### ISSUE TITLE
`servletContainer` configuration docs need updates

### ISSUE THREAD

**Issue by johnjaylward** [gretty-gradle-plugin/gretty-doc#4]
`servletContainer` says that `tomcat7` and `tomcat8` are valid choices, but the release notes for version 3+ of the plugin say that tomcat 7 and 8 support has been removed. Does Tomcat 9 support work, or has Tomcat been dropped altogether?

ref: https://gretty-gradle-plugin.github.io/gretty-doc/Gretty-configuration.html

Not sure if it shows up in other places in the docs.

**Comment by javabrett** [comment]
Tomcat 8.5 and 9.0 remain supported. There is a known issue in Tc 9.0.14+ that will be fixed in TC 9.0.31 when released https://github.com/gretty-gradle-plugin/gretty/issues/136 .
